Repository founderswap/swap-anything, pull requests merged in 2023-12, with the labels that each got.

#38 37 add large dataset testing
  README.md
  tests/unit_test/swapanything_test/test_large_data.py
Labels: enhancement

#34 33 add match selector
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/workflows/test.yaml
  README.md
  environment.yml
  pyproject.toml
  src/swapanything/backend/__init__.py
  src/swapanything/backend/_base.py
  src/swapanything/backend/simple.py
  src/swapanything/select.py
  tests/unit_test/swapanything_test/backend/test__base.py
  tests/unit_test/swapanything_test/backend/test_simple.py
  tests/unit_test/swapanything_test/test_large_data.py
  tests/unit_test/swapanything_test/test_select.py
Labels: enhancement

#29 First release with base solver
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/workflows/python-publish.yml
  .github/workflows/test.yaml
  README.md
  environment.yml
  pyproject.toml
  src/swapanything/backend/__init__.py
  src/swapanything/backend/_base.py
  src/swapanything/backend/simple.py
  src/swapanything/select.py
  tests/unit_test/swapanything_test/backend/test__base.py
  tests/unit_test/swapanything_test/backend/test_simple.py
  tests/unit_test/swapanything_test/test_large_data.py
  tests/unit_test/swapanything_test/test_select.py
Labels: help wanted

#40 v0.1
  docs/api-reference/swapanything/backend/airtable.md
  docs/api-reference/swapanything/backend/simple.md
  docs/api-reference/swapanything/index.md
  docs/api-reference/swapanything/select.md
  docs/getting-started.md
  docs/getting-started/index.md
  docs/how-to/index.md
  docs/index.md
  docs/user-guide/index.md
  mkdocs.yml
Labels: documentation, enhancement
